# Generated by Django 5.2.3 on 2025-08-02 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Parent Account'),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_periods', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='Closed By'),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='accounting.accounttype', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='budget',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='budget',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='budget',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='inventory.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='Parent Cost Center'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.costcenter', verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='currency',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_history', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounting.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='accounting.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='inventory.item', verbose_name='Item'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['branch', 'code'], name='accounting__branch__1c8440_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['fiscal_year', 'start_date', 'end_date'], name='accounting__fiscal__c5b127_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='accounttype',
            index=models.Index(fields=['branch', 'code'], name='accounting__branch__07b069_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttype',
            index=models.Index(fields=['category'], name='accounting__categor_0b0715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['branch', 'code'], name='accounting__branch__4f912e_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['parent', 'is_header'], name='accounting__parent__239053_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['branch', 'code', 'fiscal_year'], name='accounting__branch__790e71_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['account', 'cost_center', 'item'], name='accounting__account_214913_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('branch', 'code', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['branch', 'code'], name='accounting__branch__82aa57_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_default'], name='accounting__is_defa_b63f33_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='currency_positive_exchange_rate'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['branch', 'code'], name='accounting__branch__76de4a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'account_nature'], name='accounting__account_ef8b34_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_header', 'is_hidden', 'stop_sales'], name='accounting__is_head_3b08ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('commission_ratio__gte', 0), ('commission_ratio__lte', 100)), name='valid_commission_ratio'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('branch', 'code')},
        ),
        migrations.AddIndex(
            model_name='currencyhistory',
            index=models.Index(fields=['currency', 'created_at'], name='accounting__currenc_eab9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['branch', 'fiscal_year'], name='accounting__branch__90f329_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['account', 'item'], name='accounting__account_227aa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('branch', 'account', 'item', 'fiscal_year')},
        ),
    ]
