# Generated by Django 5.2.3 on 2025-06-25 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='budget',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='User responsible for this cost center', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent cost center in hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.costcenter', verbose_name='Parent Cost Center'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budget',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='currency',
            name='branch',
            field=models.ForeignKey(help_text='Branch this currency belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.ForeignKey(blank=True, help_text='Default currency for this account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_history', to='organization.branch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Changed By'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='accounting.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='currencyhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.account'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.branch'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['branch'], name='accounting__branch__b1bdd7_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['start_date'], name='accounting__start_d_101520_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['end_date'], name='accounting__end_dat_e06b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingperiod',
            index=models.Index(fields=['fiscal_year'], name='accounting__fiscal__58300a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('branch', 'period_code')},
        ),
        migrations.AddIndex(
            model_name='accounttype',
            index=models.Index(fields=['branch'], name='accounting__branch__9a039a_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttype',
            index=models.Index(fields=['category'], name='accounting__categor_0b0715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='accounttype',
            unique_together={('branch', 'type_code')},
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['branch'], name='accounting__branch__93bf03_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['parent'], name='accounting__parent__4b7960_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_header'], name='accounting__is_head_5de689_idx'),
        ),
        migrations.AddIndex(
            model_name='costcenter',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_c6090c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('branch', 'cost_center_code')},
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['branch'], name='accounting__branch__c34b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['budget_code'], name='accounting__budget__d5e1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fiscal_year'], name='accounting__fiscal__62b0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['account'], name='accounting__account_462bf0_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['cost_center'], name='accounting__cost_ce_203910_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['item'], name='accounting__item_id_a7f426_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('branch', 'budget_code', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['branch'], name='accounting__branch__3f6356_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['currency_code'], name='accounting__currenc_2f8a11_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_local'], name='accounting__is_loca_a91624_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_default'], name='accounting__is_defa_b63f33_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_610118_idx'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='currency_positive_exchange_rate'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('upper_limit__gte', 0)), name='currency_non_negative_upper_limit'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('lower_limit__gte', 0)), name='currency_non_negative_lower_limit'),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('branch', 'currency_code')},
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['branch', 'parent'], name='accounting__branch__487d53_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_code'], name='accounting__account_6b3bad_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_name'], name='accounting__account_866933_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='accounting__account_1a6511_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_nature'], name='accounting__account_a622cd_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_header'], name='accounting__is_head_d096a2_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_28dd04_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['stop_sales'], name='accounting__stop_sa_143a85_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['current_balance'], name='accounting__current_59d075_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('commission_ratio__gte', 0), ('commission_ratio__lte', 100)), name='valid_commission_ratio'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='non_negative_credit_limit'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('debit_limit__gte', 0)), name='non_negative_debit_limit'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('branch', 'account_code')},
        ),
        migrations.AddIndex(
            model_name='currencyhistory',
            index=models.Index(fields=['currency', 'created_at'], name='accounting__currenc_eab9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyhistory',
            index=models.Index(fields=['branch', 'created_at'], name='accounting__branch__da93f7_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['branch'], name='accounting__branch__113cca_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['account'], name='accounting__account_b47f21_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['item'], name='accounting__item_id_07b1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='openingbalance',
            index=models.Index(fields=['fiscal_year'], name='accounting__fiscal__bda827_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openingbalance',
            unique_together={('branch', 'account', 'item', 'fiscal_year')},
        ),
    ]
