services:
  core:
    build:
      context: ./backend
    container_name: hinsell_backend
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
    volumes:
      - ./staticfiles:/app/staticfiles:z
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  celery:
    build:
      context: ./backend
      dockerfile: ../infrastructure/celery/celery-worker/Dockerfile
    container_name: hinsell_celery
    env_file: .env
    depends_on:
      - db
      - redis
      - core
    networks:
      - mynetwork
    command: ["celery", "-A", "core", "worker", "--loglevel=info"]
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: hinsell_redis
    networks:
      - mynetwork
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: hinsell_postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5433:5432"
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
    restart: unless-stopped
    
networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
  redis_data: