# Generated by Django 5.2.3 on 2025-08-02 08:12

import apps.shared.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this record', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last updated')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this record is active')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been soft deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft deleted', null=True)),
                ('file', models.FileField(help_text='Media file (image, video, document)', upload_to='media/%Y/%m/%d/', validators=[apps.shared.models.StableFileExtensionValidator(allowed_extensions=['avi', 'bmp', 'doc', 'docx', 'gif', 'jpeg', 'jpg', 'mkv', 'mov', 'mp4', 'pdf', 'png', 'txt', 'webm', 'webp']), apps.shared.models.validate_file_size], verbose_name='File')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=100, verbose_name='Alt Text')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying media', verbose_name='Display Order')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], help_text='Automatically detected media type', max_length=20, verbose_name='Media Type')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size')),
                ('image_dimensions', models.CharField(blank=True, help_text='Image dimensions (e.g., 1920x1080)', max_length=50, null=True, verbose_name='Image Dimensions')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['media_type', 'display_order'], name='shared_medi_media_t_b39eda_idx'), models.Index(fields=['is_active'], name='shared_medi_is_acti_9ac545_idx'), models.Index(fields=['is_deleted'], name='shared_medi_is_dele_c9b03f_idx')],
            },
        ),
    ]
