# Generated by Django 5.2.3 on 2025-08-01 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Media file (image, video, etc.)', upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['bmp', 'doc', 'docx', 'jpeg', 'png', 'jpg', 'mp4', 'avi', 'webm', 'txt', 'gif', 'mkv', 'mov', 'pdf', 'webp'])], verbose_name='File'),
        ),
    ]
