# Generated by Django 5.2.3 on 2025-08-01 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(help_text='Media file (image, video, etc.)', upload_to='media/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'bmp', 'mkv', 'webm', 'pdf', 'doc', 'gif', 'jpeg', 'jpg', 'webp', 'txt', 'png', 'mov', 'docx'])], verbose_name='File'),
        ),
    ]
